M48
; DRILL file {KiCad (5.99.0-11535-gf6cac49802)} date Tue Jul 27 22:48:33 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-07-27T22:48:33-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-11535-gf6cac49802)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.1378Y-3.2677
X5.7677Y-3.2677
T0
M30
